services:
  mariadb:
    image: mariadb:11.8
    container_name: moodle-db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend

  moodle:
    image: bitnami/moodle:5.0.2
    container_name: moodle-app
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_USER=${MARIADB_USER}
      - MOODLE_DATABASE_PASSWORD=${MARIADB_PASSWORD}
      - MOODLE_DATABASE_NAME=${MARIADB_DATABASE}
      - MOODLE_REVERSE_PROXY=yes
      - MOODLE_SITE_URL=https://${MOOODLE_SITE_DOMAIN}
      - MOODLE_USERNAME=${MOODLE_USERNAME}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
    volumes:
      - ./moodle_data:/bitnami/moodle
      - ./moodledata_data:/bitnami/moodledata
    expose:
      - "8080"
    labels:
      # Включаем Traefik для этого контейнера
      - traefik.enable=true
      - traefik.http.routers.moodle-router.rule=Host(`${MOOODLE_SITE_DOMAIN}`)
      - traefik.http.routers.moodle-router.entrypoints=websecure
      - traefik.http.routers.moodle-router.tls=true
      - traefik.http.routers.moodle-router.tls.certresolver=cert-resolver
      # Указываем, на какой порт внутри контейнера направлять трафик
      - traefik.http.services.moodle-service.loadbalancer.server.port=8080
    networks:
      - backend
      - frontend

# Определяем сети для изоляции сервисов
networks:
  frontend:
    name: traefik-proxy-network
    external: true
  backend:
    name: moodle-backend-network
    external: false